### Numpy'in ana konusu homojen çok boyutlu diziler ve nümerik işlemlerdir.

In [3]:
import numpy as np

Bir numpy dizisi şöyle tanımlanır (tek boyutlu vektör)

In [14]:
a=np.array([1,2,5])

In [16]:
type(a)

numpy.ndarray

* Numpy'ın dizi sınıfı ndarray'dir. 
* Standart Python array sınıfı tek boyutlu dizilerle ve daha kısıtlı işlem yapmayı sağlar. 
* ndarray ise çok boyutlu dizilerle çalışmayı sağlar ve daha çok fonksiyon sunur.

Bir dizinin boyutları:

In [17]:
a.shape

(3,)

NumPy'de boyutlar eksen olarak adlandırılır. Yukarıdaki dizi bir eksenlidir (axis).

In [18]:
b=np.array([
            [1,2,3],
            [4,5,6]
           ])

In [19]:
b.shape

(2, 3)

Yukarıdaki ndarray iki eksenlidir(axis), ya da iki boyutludur (dimension) denebilir (2 satır, 3 sütundan oluşan 2x3 matris)

In [26]:
b.shape[0] #shape bşr tuple'dır ve indislenerek elemanları alınabilir

2

Bir ndarray'in eksen sayısı ndim komutu ile alınır. (number of dimensions)

In [22]:
print(a.ndim)
print(b.ndim)

1
2


ndarray'deki toplam eleman sayısı size komutu ile alınır. 

In [25]:
print(a.size)
print(b.size)

3
6


In [ ]:
Dizideki her bir elemanın bellekte kaç byte yer kapladığını bulmak için:

In [42]:
a.itemsize

4

In [43]:
c=np.array([2.1,2.5,3.2])

In [44]:
c.itemsize

8

Dizideki elemanların türleri:

In [33]:
a.dtype

dtype('int32')

In [41]:
a.dtype.name

'int32'

In [45]:
c.dtype.name

'float64'

Otomatik dizi oluşturma

In [49]:
x=np.zeros((3,4))  # tüm elemanları sıfır olan 3 satır, 4 sütun dizi  (varsayılan eleman türü float)
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
x.dtype

dtype('float64')

In [51]:
x=np.zeros((3,4), dtype=np.int16) 
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [52]:
x.dtype

dtype('int16')

In [53]:
y=np.ones((3,4)) #3x4 birler dizisi, varsayılan tür float
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
z=np.empty((3,3)) #rastgele elemanlardan oluşan bir dizi
z

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.97228779e-321],
       [1.08221785e-311, 0.00000000e+000, 1.08300429e-311]])

Sıralı diziler oluşturmak için

In [67]:
d1=np.arange(10,40,5) #arange fonksiyonu: 10'dan 40'a (üst sınır hariç) kadar 5'er artışla dizi
d1

array([10, 15, 20, 25, 30, 35])

In [70]:
d2=np.arange(0,2,0.3) #0 ile 2 arası 0.3 artışla eleman oluştur
d2

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

arange fonksiyonunda iki sınır aralığı içinde belirtilen  artışla ilerlenerek eleman oluşturulur. dizinin kaç elemandan oluşacağı önceden belli değildir, artış miktarına göre sayı değişir.

* iki sınır değer aralığında belirli sayıda eleman üretmek için (burada artış miktarı dinamik belirlenir):

In [73]:
d3=np.linspace( 0, 2, 9 ) # 0 ile 2 arasında 9 tane sayı  #linspace üst sınırı da aralığa dahil eder
d3

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])